export enum CHECKPOINT_STATUS {
  TURN_OFF,
  CHOOSING,
  TURN_ON,
}

export enum ALGORITHM_ACTION_STATUS {
  IDLE,
  RUNNING,
  DONE,
}

export const BOARD = {
  INITIAL_ROWS: 15,
  INITIAL_COLS: 20,
  DEFAULT_START_NODE_ROW: 4,
  DEFAULT_START_NODE_COL: 4,
  DEFAULT_FINISH_NODE_ROW: 10,
  DEFAULT_FINISH_NODE_COL: 16,
};
